src/FastRoute.php

| Fixed issues  | https://github.com/yiisoft/router/issues/1

Add group support

---

src/FastRoute.php
tests/FastRouteTest.php

| Tests pass?   | ?
| Fixed issues  | https://github.com/yiisoft/router/issues/5

Draft alternative implementation for groups

---

src/FastRoute.php
tests/FastRouteTest.php

Escape delimiter in parameter pattern

---

src/FastRoute.php

Updated implementation of the UrlGeneratorInterface which has been changed with [this PR](https://github.com/yiisoft/router/pull/13)

Updated implementing of UrlGeneratorInterface

---

src/FastRoute.php

| Fixed issues  | #12, yiisoft/router#16

Fix groups

---

src/FastRoute.php

| Fixed issues  | fixed adding group middleware to a route
I'm working on the router/Group middleware test.
This bugfix is critical. Accept PR as soon as possible.

Add getCurrentRoute() method, fix group middleware

---

src/FastRoute.php
tests/UrlGeneratorTest.php

| New feature?  |❌
Fixed request parameters. Parameters that has not been substituted will be added as a query string.

Fix url params

---

README.md
src/FastRoute.php
tests/UrlGeneratorTest.php
tests/UrlMatcherTest.php

Updated tests, docs and minor optimization 

---

src/FastRoute.php
tests/UrlGeneratorTest.php

Fixed URLs generation for nested groups, improved tests.

Fix generation URLs for nested groups

---

src/FastRoute.php
tests/UrlGeneratorTest.php

Add absolute url generation

---

src/UrlMatcher.php
tests/UrlMatcherTest.php

Fix route injection, add tests

---

composer.json
src/FastRouteCache.php
src/UrlMatcher.php
tests/UrlMatcherTest.php

Move caching into separate class

---

composer.json
config/common.php

Add config

---

config/common.php
config/web.php
src/UrlGenerator.php
src/UrlMatcher.php
tests/UrlGeneratorTest.php
tests/UrlMatcherTest.php

Merge https://github.com/yiisoft/router/pull/77 before

Make UrlMatcher optional

---

composer.json
src/UrlGenerator.php
src/UrlMatcher.php
tests/UrlMatcherTest.php

Merge with https://github.com/yiisoft/router/pull/78

Remove getLastMatchedRequest, add getCurrentUri

---

src/UrlGenerator.php
tests/UrlGeneratorTest.php

Fix generateAbsoluteUrl

---

config/common.php
config/params.php
src/UrlGenerator.php
src/UrlMatcher.php
tests/UrlGeneratorTest.php
tests/UrlMatcherTest.php

Encode params

---

config/common.php
config/params.php
config/web.php
src/FastRouteCache.php

| Is bugfix?    | Yes
| New feature?  | No
| Breaks BC?    | No
| Fixed issues  | #66

Package name as key in configuration

---

src/UrlMatcher.php
tests/UrlGeneratorTest.php
tests/UrlMatcherTest.php

Merge after https://github.com/yiisoft/router/pull/101

Fix tests, add static routes support

---

config/common.php

Merge after https://github.com/yiisoft/factory/pull/78

Adopt configs to new factory syntax

---

src/UrlGenerator.php
src/UrlMatcher.php
tests/UrlMatcherTest.php

Adjust to yiisoft/router changes

---

src/UrlGenerator.php
src/UrlMatcher.php
tests/UrlMatcherTest.php

| Fixed issues  | Adopt yiisoft/router#110

Adjust to router changes

---

tests/UrlGeneratorTest.php
tests/UrlMatcherTest.php

| Fixed issues  | Adjust to yiisoft/router#115

Adjust tests to router changes

---

src/UrlGenerator.php
src/UrlMatcher.php
tests/UrlGeneratorTest.php
tests/UrlMatcherTest.php

| Breaks BC?    | ✔️/❌
| Fixed issues  | Adopt yiisoft/router#117

Adopt UrlMatcher changes

---

src/UrlMatcher.php
tests/UrlGeneratorTest.php
tests/UrlMatcherTest.php

| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

Adopt router changes

---

src/UrlMatcher.php
tests/UrlMatcherTest.php

:warning: Merge after https://github.com/yiisoft/router/pull/128

Rename parameters to arguments

---

src/UrlGenerator.php
src/UrlMatcher.php

| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
:warning: Merge after https://github.com/yiisoft/router/pull/138

Adapt to router changes

---

src/UrlMatcher.php
tests/Support/NotFoundRouteParser.php
tests/UrlGeneratorTest.php
tests/UrlMatcherTest.php

More tests + minor refactoring and cleanup

---

src/UrlGenerator.php
tests/UrlGeneratorTest.php

Fix locale-based urls generation without CurrentRoute

---

composer.json
psalm.xml
src/UrlGenerator.php
src/UrlMatcher.php

| Fixed issues  | https://github.com/yiisoft/router/issues/154 https://github.com/yiisoft/router-fastroute/issues/89
Required https://github.com/yiisoft/router/pull/155

Cast URL parameters to string + Psalm level 1

---

config/common.php
src/UrlGenerator.php
src/UrlMatcher.php
tests/UrlGeneratorTest.php

Fix #95
Merge after https://github.com/yiisoft/router/pull/156

New locales based on pattern

---

src/UrlGenerator.php
tests/UrlGeneratorTest.php

Fix empty argument

---

src/UrlGenerator.php
src/UrlMatcher.php
tests/UrlGeneratorTest.php
tests/UrlMatcherTest.php

| Readability fix  | according to https://github.com/yiisoft/docs/issues/155, chain calls must be put on separate lines.

Separate chain calls

---

CHANGELOG.md
composer.json
tests/UrlMatcherTest.php

Update `yiisoft/router` version to `^1.1`

---

CHANGELOG.md
composer.json

| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

Update `router` version to `^2.1`

---

.github/workflows/rector.yml
composer.json
tests/ConfigTest.php

Add test disabled cache in params + Improve rector CI

---

.github/workflows/rector.yml
composer.json

Improve rector CI

---

CHANGELOG.md
config/di.php
config/params.php

Add UrlGenerator host and scheme properties to package configuration params
